spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    initialization-mode: always
    name: localdb
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./target/localdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    platform: h2
  h2:
    console:
      enabled: true
